source.. = src/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               plugin.properties,\
               EPL-2.0.html,\
               icons/,\
               .options,\
               resources/,\
               schema/,\
               OSGI-INF/
src.includes = schema/

# https://codeiseasy.wordpress.com/2013/03/08/tycho-and-jdt-null-analysis/
# JDT Null Analysis for Eclipse
additional.bundles = org.eclipse.jdt.annotation
# JDT Null Analysis types for Tycho
jars.extra.classpath = platform:/plugin/org.eclipse.jdt.annotation
